# Generated by Django 2.1.5 on 2019-03-10 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20190310_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_phonenumber',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
