# Generated by Django 2.1.5 on 2019-04-07 14:52

import catalog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20190329_2204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=catalog.models.get_image_filename, verbose_name='Image')),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='file',
        ),
        migrations.RemoveField(
            model_name='item',
            name='file_name',
        ),
        migrations.AddField(
            model_name='images',
            name='file_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='catalog.Item'),
        ),
    ]
