# Generated by Django 2.1.5 on 2019-05-12 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20190407_1652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='file_name',
            new_name='post',
        ),
    ]
