# Generated by Django 2.1.5 on 2019-05-12 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20190512_1858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='post',
            new_name='item',
        ),
    ]
