# Generated by Django 3.0.8 on 2020-08-03 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20190522_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='observing',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
